INSERT INTO `document_type` (`id`, `name`, `created_at`, `updated_at`) VALUES
(1, 'DOCUMENTO PESSOAL', NULL, NULL),
(2, 'COMPROVANTE DE RENDA', NULL, NULL),
(3, 'COMPROVANTE DE RESIDÊNCIA', NULL, NULL),
(4, 'CONSULTA FINANCEIRA', NULL, NULL),
(6, 'CONTRATO', NULL, NULL),
(7, 'BOLETO', NULL, NULL),
(8, 'COMPROVANTE DE PAGAMENTO', NULL, NULL),
(9, 'CONTRATO DE COMPRA', NULL, NULL),
(10,'CONTRATO DE VENDA', NULL, NULL),
(13,'BOLETO DE COMPRA', '2023-04-19 13:27:22', NULL),
(14,'BOLETO DE COMISSÃO', '2023-04-19 13:27:31', NULL);

/* Atualizado em 10/04 às 10h
